# This is just a notebook for numpy learn based on runoob.

NumPy 应用
NumPy 通常与 SciPy（Scientific Python）和 Matplotlib（绘图库）一起使用， 这种组合广泛用于替代 MatLab，是一个强大的科学计算环境，有助于我们通过 Python 学习数据科学或者机器学习。

SciPy 是一个开源的 Python 算法库和数学工具包。

SciPy 包含的模块有最优化、线性代数、积分、插值、特殊函数、快速傅里叶变换、信号处理和图像处理、常微分方程求解和其他科学与工程中常用的计算。

Matplotlib 是 Python 编程语言及其数值数学扩展包 NumPy 的可视化操作界面。它为利用通用的图形用户界面工具包，如 Tkinter, wxPython, Qt 或 GTK+ 向应用程序嵌入式绘图提供了应用程序接口（API）。



In [29]:
# -*- coding:utf-8 -*-

import numpy as np

In [30]:
# ndarray : N-dims array hold same data-type.
# numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

data = np.array([1,2,3])
print(data)

print("===============")
data = np.array([[1,2],[3,4]])
print(data)

print("===============")
data = np.array([1,2,3,4,5], ndmin = 2)
print(data)

print("===============")
data = np.array([1,  2,  3], dtype = complex)  
print(data)

[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]


# dtype
数据类型对象 (dtype)
数据类型对象是用来描述与数组对应的内存区域如何使用，这依赖如下几个方面：

数据的类型（整数，浮点数或者 Python 对象）
数据的大小（例如， 整数使用多少个字节存储）
数据的字节顺序（小端法或大端法）
在结构化类型的情况下，字段的名称、每个字段的数据类型和每个字段所取的内存块的部分
如果数据类型是子数组，它的形状和数据类型
字节顺序是通过对数据类型预先设定"<"或">"来决定的。"<"意味着小端法(最小值存储在最小的地址，即低位组放在最前面)。">"意味着大端法(最重要的字节存储在最小的地址，即高位组放在最前面)。

dtype 对象是使用以下语法构造的：

numpy.dtype(object, align, copy)
object - 要转换为的数据类型对象
align - 如果为 true，填充字段使其类似 C 的结构体。
copy - 复制 dtype 对象 ，如果为 false，则是对内置数据类型对象的引用


In [50]:
import numpy as np

student_dtype = np.dtype([("name","S20"),("age","i1"),("marks", "f4")])
data = np.array([('dan',28,1),("jessica",18,75)], dtype=student_dtype)

print(data)

print(data['name'])

print(len(data['name']))

[(b'dan', 28,  1.) (b'jessica', 18, 75.)]
[b'dan' b'jessica']
2


In [32]:
# # NumPy 数组属性
# 本章节我们将来了解 NumPy 数组的一些基本属性。

# NumPy 数组的维数称为秩（rank），一维数组的秩为 1，二维数组的秩为 2，以此类推。

# 在 NumPy中，每一个线性的数组称为是一个轴（axis），也就是维度（dimensions）。比如说，二维数组相当于是两个一维数组，其中第一个一维数组中每个元素又是一个一维数组。所以一维数组就是 NumPy 中的轴（axis），第一个轴相当于是底层数组，第二个轴是底层数组里的数组。而轴的数量——秩，就是数组的维数。

# 很多时候可以声明 axis。axis=0，表示沿着第 0 轴进行操作，即对每一列进行操作；axis=1，表示沿着第1轴进行操作，即对每一行进行操作。

# NumPy 的数组中比较重要 ndarray 对象属性有：

# 属性	说明
# ndarray.ndim	秩，即轴的数量或维度的数量
# ndarray.shape	数组的维度，对于矩阵，n 行 m 列
# ndarray.size	数组元素的总个数，相当于 .shape 中 n*m 的值
# ndarray.dtype	ndarray 对象的元素类型
# ndarray.itemsize	ndarray 对象中每个元素的大小，以字节为单位
# ndarray.flags	ndarray 对象的内存信息
# ndarray.real	ndarray元素的实部
# ndarray.imag	ndarray 元素的虚部
# ndarray.data	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。

In [33]:
import numpy as np 
 
a = np.arange(24)  
print(a)
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print(b)
print (b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [34]:
a = np.array([[1,2,3],[4,5,6]])

print(" a = %s" % a)

print("a.ndim : %s " % a.ndim)
print("a.shape :")
print(a.shape)

# reshape array by shape property
a.shape = (3,2)
print("a.shape :")
print(a.shape)
print("a = %s" % a)

# reshape array by reshap method
b = a.reshape(2,3)
print("a = %s" % a)
print("b = %s" % b)

 a = [[1 2 3]
 [4 5 6]]
a.ndim : 2 
a.shape :
(2, 3)
a.shape :
(3, 2)
a = [[1 2]
 [3 4]
 [5 6]]
a = [[1 2]
 [3 4]
 [5 6]]
b = [[1 2 3]
 [4 5 6]]


In [35]:
# ndarray.itemsize 以字节的形式返回数组中每一个元素的大小。



# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
 
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


In [51]:
# ndarray 数组除了可以使用底层 ndarray 构造器来创建外，也可以通过以下几种方式来创建。
import pickle

d = np.empty((2,3), dtype = student_dtype)
print(d)
print(d[0][0]["name"])
print(type(d[0][0]["name"]))
# print(pickle.loads(d[0][0]["name"]))

[[(b'\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\n\x00\xfb\x19',   1, -4.65661287e-10)
  (b'2\xfb\x19\x01\x00\x00\x00\xe82\xfb\x19\x01\x00\x00\x00\x18<\xfb\x19\x01',   0,  1.26953125e-02)
  (b'\xfb\x19\x01\x00\x00\x00\xc0<\xfb\x19\x01\x00\x00\x00\xf8<\xfb\x19\x01',   0, -9.64144623e+35)]
 [(b'\x19\x01\x00\x00\x00\x185\xfb\x19\x01\x00\x00\x00(8\xfb\x19\x01',   0,  2.59775052e-23)
  (b'\x01\x00\x00\x00h=\xfb\x19\x01\x00\x00\x00\x107\xfb\x19\x01', -96,  2.82819165e-38)
  (b'\x00\x00\x00\x10>\xfb\x19\x01\x00\x00\x00H>\xfb\x19\x01\x00\x00\x00\x80',  62,  1.01155532e-40)]]
b'\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\n\x00\xfb\x19'
<class 'numpy.bytes_'>


In [66]:
import numpy as np
a = np.zeros((2,3))
print(a)

a = np.zeros((2,3),dtype = "i1")
print(a)

print(a.data)
print(a.dtype)
print(a.ndim)
print(a.itemsize)
print(a.real)
print(a.imag)
print(a.flags)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
int8
2
1
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [67]:
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [69]:
one = np.ones(5)
print(one)

one = np.ones((2,3), dtype= np.int)
print(one)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [88]:
a = (1,3,5)
print(np.asarray(a, dtype = np.int))

b = [(1,3,5),(2,4,6)]
print(np.asarray(b, dtype = np.float))

s = "Hello world"
print(np.asarray(s, dtype = "S1"))
print(np.asarray(s, dtype = 'S20'))

s = b"Hello world"
cur_s = np.frombuffer(s, dtype = "S1")
print(cur_s)

# AttributeError: 'str' object has no attribute '__buffer__'
# As python3 hold unicode as default type for str, we need to append char 'b' before str object.
# s = "Hello world"
# cur_s = np.frombuffer(s, dtype = "S1")
# print(cur_s)

# ValueError: buffer size must be a multiple of element size
# cur_s = np.frombuffer(s, dtype = "S10")
cur_s = np.frombuffer(s, dtype = "S11")
print(cur_s)

cur_s = np.frombuffer(s, dtype = "S1", count = 10)
print(cur_s)

cur_s = np.frombuffer(s, dtype = "S2", count = 5)
print(cur_s)


cur_s = np.frombuffer(s,dtype = "S1",count = 10, offset = 1)
print(cur_s)

[1 3 5]
[[1. 3. 5.]
 [2. 4. 6.]]
b'H'
b'Hello world'
[b'H' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
[b'Hello world']
[b'H' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l']
[b'He' b'll' b'o ' b'wo' b'rl']
[b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


In [91]:
import numpy as np

a = range(10)
iter_handler = iter(a)

print(np.fromiter(iter_handler, dtype = np.int))
print(np.fromiter(a, dtype = np.int))

print(np.fromiter(iter_handler, dtype = np.int))
print(np.fromiter(a, dtype = np.int))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
# numpy.arange
# numpy 包中的使用 arange 函数创建数值范围并返回 ndarray 对象，函数格式如下：

# numpy.arange(start, stop, step, dtype)
# 根据 start 与 stop 指定的范围以及 step 设定的步长，生成一个 ndarray。

# 参数说明：

# 参数	描述
# start	起始值，默认为0
# stop	终止值（不包含）
# step	步长，默认为1
# dtype	返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。
import numpy as np

a = np.arange(10)
print(a)

a = np.arange(10,20,2)
print(a)

a = np.arange(0, 15, 3)
print(a)

a = np.arange(0, 11, 3)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]
[ 0  3  6  9 12]
[0 3 6 9]


In [110]:
# numpy.linspace
# numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：

# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# !!! 包含stop值
a = np.linspace(1, 2, num=11)
print(a)
print("\n")

# 不输出 stop 值
a = np.linspace(1,2, num= 10, endpoint=False)
print(a)

# 输出长度为10，首末元素都是1的等差数列
print(np.linspace(1,1,10))

print(np.linspace(1,1,10).reshape(10,1))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2. ]


[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [115]:
# numpy.logspace
# numpy.logspace 函数用于创建一个于等比数列。格式如下：
# numpy.logspace 函数用于创建一个于等比数列。格式如下：

# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
# base 参数意思是取对数的时候 log 的下标。

# 参数	描述
# start	序列的起始值为：base ** start
# stop	序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
# num	要生成的等步长的样本数量，默认为50
# endpoint	该值为 ture 时，数列中中包含stop值，反之不包含，默认是True。
# base	对数 log 的底数。
# dtype	ndarray 的数据类型

a = np.logspace(1,10, num = 3)
print(a)

a = np.logspace(1,4, num = 4, base = 2)
print(a)

[1.00000000e+01 3.16227766e+05 1.00000000e+10]
[ 2.  4.  8. 16.]


In [133]:
# NumPy 切片和索引
# ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。

# ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。
a = np.arange(10)
print(a)

s = slice(2,7,2)  # 从索引 2 开始到索引 7 停止，间隔为2

print(a[s])

# 冒号 : 的解释：
# - 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。
# - 如果为 [2:]，表示从该索引开始以后的所有项都将被提取。
# - 如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项。
print(a[2:7])
print(a[2:7:2])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 3 4 5 6]
[2 4 6]


In [120]:
import numpy as np
 
#     切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。

a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [123]:
# NumPy 比一般的 Python 序列提供更多的索引方式。除了之前看到的用整数和切片的索引外，数组可以由整数数组索引、布尔索引及花式索引。

# 整数数组索引
# 以下实例获取数组中(0,0)，(1,1)和(2,0)位置处的元素。

import numpy as np 
 
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
print(x)
y = x[[0,1,2],  [0,1,0]]  
print (y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [125]:
import numpy as np 
 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：' )
print (x)
print ('\n')
rows = np.array([[0,0],[3,3]]) 
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols]  
print  ('这个数组的四个角元素是：')
print (y)

print(x[[0,0,3,3],[0,2,0,2]])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]
[ 0  2  9 11]


In [132]:
import numpy as np
 
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = a[1:3, 1:3]
c = a[1:3,[1,2]]
d = a[...,1:]
print(b)
print(c)
print(d)
print("\n")
print(a[1:2, 1:2])

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


[[5]]


In [127]:
import numpy as np 
 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]


In [128]:
import numpy as np 
 
a = np.array([np.nan,  1,2,np.nan,3,4,5])  
print (a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [129]:
import numpy as np 
 
a = np.array([1,  2+6j,  5,  3.5+5j])  
print (a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [130]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
def is_even(x):
    return x%2 == 0
print(x[is_even(x)])

[ 0  2  4  6  8 10]


In [139]:
# 花式索引
# 花式索引指的是利用整数数组进行索引。

# 花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。
# 对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；如果目标是二维数组，那么就是对应下标的行。

# 花式索引跟切片不一样，它总是将数据复制到新数组中。
import numpy as np

a = np.arange(32).reshape(8,4)
print(a)

x = a[[4,2,1,7]]
print("\n")
print(x)
print(a[4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[16 17 18 19]


In [1]:
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [7]:
# NumPy 迭代器对象 numpy.nditer 提供了一种灵活访问一个或者多个数组元素的方式。
# 迭代器最基本的任务的可以完成对数组元素的访问。
# 接下来我们使用 arange() 函数创建一个 2X3 数组，并使用 nditer 对它进行迭代。
import numpy as np

a = np.arange(6).reshape(2,3)
print(a)

for item in np.nditer(a):
    print(item, end = ",")
print("\n")

print(a.T)

for item in np.nditer(a.T):
    print(item, end = ",")
print("\n")
    

for item in np.nditer(a, order = "F"):
    print(item, end = ",")
print("\n")

for item in np.nditer(a.T, order = "C"):
    print(item, end = ",")
print("\n")

[[0 1 2]
 [3 4 5]]
0,1,2,3,4,5,

[[0 3]
 [1 4]
 [2 5]]
0,1,2,3,4,5,

0,3,1,4,2,5,

0,3,1,4,2,5,

